<a href="https://colab.research.google.com/github/jigimmie/Aiffel_jigimmie/blob/main/03_12_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<오늘의 미션>
1. 단어장 개수를 바꾸면서(10000, 5000, Nan) 6개의 ML모델을 사용해보고 accuacry와 f1-score를 비교 (표로 나타내보세요~) (벡터화는 tf-idf로 통일)

2. RNN이나 1-d cnn과 머신러닝 성능 비교

# 1. 머신러닝 모델 비교해보기

In [ ]:
from tensorflow.keras.datasets import reuters
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

In [ ]:
word_index = reuters.get_word_index(path="reuters_word_index.json")

In [ ]:
index_to_word = { index+3 : word for word, index in word_index.items() }
for index, token in enumerate(("<pad>", "<sos>", "<unk>")):
  index_to_word[index]=token

In [ ]:
decoded = []
for i in range(len(x_train)):
    t = ' '.join([index_to_word[index] for index in x_train[i]])
    decoded.append(t)

x_train = decoded
print(len(x_train))

8982

In [ ]:
decoded_test = []
for i in range(len(x_test)):
    t = ' '.join([index_to_word[index] for index in x_test[i]])
    decoded_test.append(t)

x_test = decoded_test
print(len(x_test))

2246

In [ ]:
# 벡터화 DTM, TF-idf 방법
dtmvector = CountVectorizer()

tfidf_transformer = TfidfTransformer()

x_train_dtm = dtmvector.fit_transform(x_train)
x_test_dtm= dtmvector.transform(x_test)

x_train_tfidf = tfidf_transformer.fit_transform(x_train_dtm)
x_test_tfidf = tfidf_transformer.transform(x_test_dtm)

### case1.모든단어 사용

In [ ]:
import pandas as pd

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, f1_score

# 모델 목록
models = [
    LogisticRegression(penalty='l2', max_iter=1000),
    ComplementNB(),
    LinearSVC(),
    RandomForestClassifier(n_estimators=100, random_state=0),
    GradientBoostingClassifier(),
    SGDClassifier(loss='log_loss')
]

results = []

for model in models:

    # 학습
    model.fit(x_train_tfidf, y_train)

    # 예측
    y_pred = model.predict(x_test_tfidf)

    # 평가
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')

    # 결과 저장
    results.append({
        "Model": model.__class__.__name__,
        "Accuracy": acc,
        "F1-score": f1
    })

# DataFrame 생성
results_df = pd.DataFrame(results)

print(results_df)

                        Model  Accuracy  F1-score
0          LogisticRegression  0.791630  0.451397
1                ComplementNB  0.764915  0.463985
2                   LinearSVC  0.829475  0.688698
3      RandomForestClassifier  0.744880  0.402578
4  GradientBoostingClassifier  0.768032  0.581110
5               SGDClassifier  0.794301  0.479704

#case2. 10000개 단어 사용

In [ ]:
import pandas as pd

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, f1_score

# 모델 목록
models = [
    LogisticRegression(penalty='l2', max_iter=1000),
    ComplementNB(),
    LinearSVC(),
    RandomForestClassifier(n_estimators=100, random_state=0),
    GradientBoostingClassifier(),
    SGDClassifier(loss='log_loss')
]

results = []

for model in models:

    # 학습
    model.fit(x_train_tfidf, y_train)

    # 예측
    y_pred = model.predict(x_test_tfidf)

    # 평가
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')

    # 결과 저장
    results.append({
        "Model": model.__class__.__name__,
        "Accuracy": acc,
        "F1-score": f1
    })

# DataFrame 생성
result_2 = pd.DataFrame(results)

print(result_2)

                        Model  Accuracy  F1-score
0          LogisticRegression  0.795637  0.472114
1                ComplementNB  0.770703  0.478358
2                   LinearSVC  0.829920  0.680843
3      RandomForestClassifier  0.757346  0.440226
4  GradientBoostingClassifier  0.760463  0.562521
5               SGDClassifier  0.800089  0.509566

# case3. 5000개 단어 사용

In [ ]:
import pandas as pd

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, f1_score

# 모델 목록
models = [
    LogisticRegression(penalty='l2', max_iter=1000),
    ComplementNB(),
    LinearSVC(),
    RandomForestClassifier(n_estimators=100, random_state=0),
    GradientBoostingClassifier(),
    SGDClassifier(loss='log_loss')
]

results = []

for model in models:

    # 학습
    model.fit(x_train_tfidf, y_train)

    # 예측
    y_pred = model.predict(x_test_tfidf)

    # 평가
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='macro')

    # 결과 저장
    results.append({
        "Model": model.__class__.__name__,
        "Accuracy": acc,
        "F1-score": f1
    })

# DataFrame 생성
result_3 = pd.DataFrame(results)

print(result_3)

                        Model  Accuracy  F1-score
0          LogisticRegression  0.797863  0.481380
1                ComplementNB  0.770703  0.482035
2                   LinearSVC  0.829029  0.681414
3      RandomForestClassifier  0.758682  0.427340
4  GradientBoostingClassifier  0.768032  0.587565
5               SGDClassifier  0.801425  0.511283

In [ ]:
df = pd.concat([results_df, result_2, result_3], ignore_index=True)

                         Model  Accuracy  F1-score
0           LogisticRegression  0.791630  0.451397
1                 ComplementNB  0.764915  0.463985
2                    LinearSVC  0.829475  0.688698
3       RandomForestClassifier  0.744880  0.402578
4   GradientBoostingClassifier  0.768032  0.581110
5                SGDClassifier  0.794301  0.479704
6           LogisticRegression  0.795637  0.472114
7                 ComplementNB  0.770703  0.478358
8                    LinearSVC  0.829920  0.680843
9       RandomForestClassifier  0.757346  0.440226
10  GradientBoostingClassifier  0.760463  0.562521
11               SGDClassifier  0.800089  0.509566
12          LogisticRegression  0.797863  0.481380
13                ComplementNB  0.770703  0.482035
14                   LinearSVC  0.829029  0.681414
15      RandomForestClassifier  0.758682  0.427340
16  GradientBoostingClassifier  0.768032  0.587565
17               SGDClassifier  0.801425  0.511283

In [ ]:
# Initialize the 'num_words' column
df['num_words'] = ''

# Assign 'none' for the first 6 rows (from results_df - all words)
df.loc[0:5, 'num_words'] = 'none'

# Assign 10000 for the next 6 rows (from result_2 - 10000 words)
df.loc[6:11, 'num_words'] = 10000

# Assign 5000 for the last 6 rows (from result_3 - 5000 words)
df.loc[12:17, 'num_words'] = 5000

In [ ]:
df

                         Model  Accuracy  F1-score num_words
0           LogisticRegression  0.791630  0.451397      none
1                 ComplementNB  0.764915  0.463985      none
2                    LinearSVC  0.829475  0.688698      none
3       RandomForestClassifier  0.744880  0.402578      none
4   GradientBoostingClassifier  0.768032  0.581110      none
5                SGDClassifier  0.794301  0.479704      none
6           LogisticRegression  0.795637  0.472114     10000
7                 ComplementNB  0.770703  0.478358     10000
8                    LinearSVC  0.829920  0.680843     10000
9       RandomForestClassifier  0.757346  0.440226     10000
10  GradientBoostingClassifier  0.760463  0.562521     10000
11               SGDClassifier  0.800089  0.509566     10000
12          LogisticRegression  0.797863  0.481380      5000
13                ComplementNB  0.770703  0.482035      5000
14                   LinearSVC  0.829029  0.681414      5000
15      RandomForestClassifier  0.758682  0.427340      5000
16  GradientBoostingClassifier  0.768032  0.587565      5000
17               SGDClassifier  0.801425  0.511283      5000

결과:
3개의 경우 모두, LinearSVC가 제일 결과가 좋았고
그 다음은 f-1 score 기준 gradient boosting 이 결과가 좋았다.

그리고 num_words에 따른 변화의 경우,
세 경우 다 비슷하나 미세하게 다르긴 했다.
가장 성능 좋은 LinearSVC의 경우,
세 경우 다 성능이 비슷했지만 모든 단어를 다 쓴 경우가 제일 성능이 좋았다.
그러나 전체적으로 놓고 보면 5000개 단어일때가 성능이 제일 좋았다.

왜 LinearSVC가 성능이 좋냐
- 고차원 데이터에 강함
- 희소 데이터 처리에 강함
따라서 LinearSVC 성능은 오히려 모든 단어를 다 사용했을때 성능이 좋은 것으로 추정

왜 전체적으로는 5000일때 성능이 좋았을지
- 단어 인덱스가 너무 많으면 중요하지 않은 단어(노이즈)가 껴서 overfitting될수도

# Dense NN model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout, LSTM, Dense, Dropout


# 아래 Dense의 레이어를 바꿔가며 성능을 확인해봅시다

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout

# 샘플 하나의 shape: (26506,)
inputs = Input(shape=(26506,))

x = Dense(512, activation='relu')(inputs)
x = Dropout(0.3)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.3)(x)
outputs = Dense(46, activation='softmax')(x)  # 클래스 46개

dense_model = Model(inputs=inputs, outputs=outputs)

dense_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
dense_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 26506)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 512)            │    13,571,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        65,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 46)             │         5,934 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,643,182 (52.04 MB)

 Trainable params: 13,643,182 (52.04 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# 시간이 좀 걸립니다! 한 20분정도..
dense_model.fit(x_train_tfidf, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 325s 1s/step - accuracy: 0.4867 - loss: 2.3381 - val_accuracy: 0.7501 - val_loss: 1.0982
Epoch 2/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 258s 1s/step - accuracy: 0.8146 - loss: 0.8390 - val_accuracy: 0.7986 - val_loss: 0.8865
Epoch 3/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 224s 993ms/step - accuracy: 0.8989 - loss: 0.4257 - val_accuracy: 0.8136 - val_loss: 0.8565
Epoch 4/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 218s 801ms/step - accuracy: 0.9377 - loss: 0.2497 - val_accuracy: 0.8175 - val_loss: 0.8717
Epoch 5/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 158s 698ms/step - accuracy: 0.9582 - loss: 0.1656 - val_accuracy: 0.8164 - val_loss: 0.8857
Epoch 6/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 133s 591ms/step - accuracy: 0.9641 - loss: 0.1339 - val_accuracy: 0.8097 - val_loss: 0.9249
Epoch 7/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 131s 582ms/step - accuracy: 0.9615 - loss: 0.1175 - val_accuracy: 0.8136 - val_loss: 0.9278
Epoch 8/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 102s 455ms/step - accuracy: 0.9640 - loss: 0.1153 - val_accuracy: 0.8047 - val_loss: 0.9317
Epoch 9/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 89s 399ms/step - accuracy: 0.9653 - loss: 0.1074 - val_accuracy: 0.8114 - val_loss: 0.9076
Epoch 10/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 326s 1s/step - accuracy: 0.9674 - loss: 0.0928 - val_accuracy: 0.8075 - val_loss: 0.9585

In [ ]:


y_pred_proba = dense_model.predict(x_test_tfidf)
y_pred = np.argmax(y_pred_proba, axis=1)

acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"✅ Accuracy: {acc:.4f}")
print(f"✅ F1-score: {f1:.4f}")

71/71 ━━━━━━━━━━━━━━━━━━━━ 15s 215ms/step
✅ Accuracy: 0.8001
✅ F1-score: 0.7903

ML 중에 제일 잘 나왔던 linearSVC보다 f-1 score가 훨씬 잘 나왔다.

왜 그런지를 추정해보자면...
linearsvc는 선형적인 경계만 만드는 반면 dense NN은 비선형적인 부분도 학습 가능하기에 라고 추측 가능할 것 같다.